var app = angular.module("myApp",["ui.router"])
  app.controller("indexCtrl",function($scope,$http){

  })
  app.config(function($stateProvider,$urlRouterProvider){
    $urlRouterProvider.otherwise('/login')
    $stateProvider
      .state('login',{
        url:'/login',
        templateUrl:'./views/login.html',
        controller:'loginCtrl'
      })
      .state('home',{
        url:'/home',
        views:{
          '':{templateUrl:'./views/header.html',controller:'headerCtrl'},
          'content':{templateUrl:'./views/home.html',controller:'homeCtrl'},
          'footer':{templateUrl:'./views/footer.html',controller:'footerCtrl'}
        }
      })
      .state('up',{
        url:'/up',
        template:'up'
      })
      .state('coffee',{
        url:'/coffee',
        views:{
          '':{templateUrl:'./views/header.html',controller:'headerCtrl'},
          'content':{template:'coffee'}
        }
      })
      .state('tea',{
        url:'/tea',
        views:{
          '':{templateUrl:'./views/header.html',controller:'headerCtrl'},
          'content':{template:'tea'}
        }
      })
      .state('menu',{
        url:'/menu',
        views:{
          '':{templateUrl:'./views/header.html',controller:'headerCtrl'},
          'content':{template:'menu'}
        }
      })
      .state('coffeehouse',{
        url:'/coffeehouse',
        views:{
          '':{templateUrl:'./views/header.html',controller:'headerCtrl'},
          'content':{template:'coffeehouse'}
        }
      })
      .state('social',{
        url:'/social',
        views:{
          '':{templateUrl:'./views/header.html',controller:'headerCtrl'},
          'content':{template:'social'}
        }
      })
      .state('starbucks',{
        url:'/starbucks',
        views:{
          '':{templateUrl:'./views/header.html',controller:'headerCtrl'},
          'content':{template:'starbucks'}
        }
      })
      .state('blog',{
        url:'/blog',
        views:{
          '':{templateUrl:'./views/header.html',controller:'headerCtrl'},
          'content':{template:'blog'}
        }
      })
      .state('gift',{
        url:'/gift',
        views:{
          '':{templateUrl:'./views/header.html',controller:'headerCtrl'},
          'content':{template:'gift'}
        }
      })
  })